import { useState, useEffect } from 'react';
import type { CSSProperties } from 'react';
import { useQuery, useMutation, useAction } from 'convex/react';
import { api } from '../../convex/_generated/api';
import { type User } from '../lib/auth';
import { useUILang } from '../lib/i18n';

interface Prefs {
  _id?: string;
  userId?: string;
  name: string;
  role?: string;
  bio?: string;
  audience?: string;
  tone?: string;
  avoid?: string;
  lang?: string;
  apikey?: string;
  projects?: string;
  stack?: string;
  contentPillars?: string[];
}

interface Props {
  user: User;
  prefs: Prefs | null;
  search: string;
  demoMode: boolean;
  autoGenerate?: boolean;
  onAutoGenerateDone?: () => void;
}

const TONES = ['all', 'builder', 'insight', 'story', 'opinion', 'tactical'];

const TONE_COLORS: Record<string, string> = {
  builder: '#6b4fff',
  insight: '#10b981',
  story: '#f59e0b',
  opinion: '#ef4444',
  tactical: '#0077b5',
  storytelling: '#f59e0b',
  educational: '#10b981',
  motivational: '#6b4fff',
  conversational: '#8b6fff',
  professional: '#60607a',
  informative: '#0077b5',
};

const POST_LANGUAGES = [
  { code: 'English', label: 'EN' },
  { code: 'Ukrainian', label: 'UK' },
  { code: 'German', label: 'DE' },
  { code: 'French', label: 'FR' },
  { code: 'Spanish', label: 'ES' },
];

function toneColor(tone: string) {
  const k = tone.toLowerCase();
  return TONE_COLORS[k] || 'var(--t3)';
}

const DEMO_POSTS = [
  {
    _id: 'demo1',
    tone: 'Builder',
    angle: 'My AI stack for solo founders',
    content: "I replaced a 4-person team with this AI stack. Revenue: the same. Delivery: faster.\n\n→ Claude Code — architecture, complex logic, debugging\n→ Cursor — daily coding with project context\n→ Claude Design — first-pass UI wireframes\n→ Supabase — backend with auth + RLS\n→ Vercel — deploys in under 60 seconds\n\nThe workflow:\n1. Describe user behavior, not features\n2. Claude proposes 2–3 architecture approaches\n3. Pick the simplest one that scales to 1,000 users\n4. Ship with a feature flag and monitor\n\nSolo + AI = different leverage. You can't parallelize everything — but you can own every decision.\n\n💡 Start with one tool. Add the next only when you feel the gap.\n\n#BuildInPublic #AITools #SaaS #SoloFounder",
    status: 'active',
  },
  {
    _id: 'demo2',
    tone: 'Builder',
    angle: 'The system prompt that changed how I work with AI',
    content: "One system prompt. I use it before writing a single line of code in every project.\n\n---\nYou are a Senior Product Engineer on this project.\nStack: [your stack]\n\nBefore implementing anything:\n1. Ask if something is unclear\n2. Propose 2–3 approaches with trade-offs\n3. Flag architectural risks proactively\n\nAfter each implementation:\n✅ What was done\n⚠️ Potential issues\n🔄 What you'd do differently with more time\n---\n\nBefore: Claude completed tasks and stayed quiet about problems.\nAfter: \"there's an N+1 query risk here\" or \"this won't scale past 500 concurrent users.\"\n\nThe difference between a code generator and a thought partner: you give it permission to think, not just execute.\n\n#ClaudeCode #AITools #BuildInPublic #ProductDesign",
    status: 'active',
  },
  {
    _id: 'demo3',
    tone: 'Builder',
    angle: 'From idea to first paying client in 6 days',
    content: "I built a voice AI for restaurants and landed the first paying client in 6 days. No marketing. No pitch deck.\n\nDay 1 — Math before Figma:\nMissed call = ~$50 lost reservation × 10 calls × 20 evenings = $10,000/month lost\nMy price: $249/month → Client ROI: 40×\n\nDay 2 — Architecture with Claude:\n\"Propose an architecture for minimum latency. No code yet.\"\n\nDay 3 — Stack chosen by UX metric:\nDeepdram over Whisper: 80ms vs 800ms. After 1.5s of silence, callers hang up.\n\nDay 4 — Transactional onboarding:\n4 APIs, one transaction. Any failure → full rollback.\n\nDay 5 — Live demo:\n\"Does it really do that on its own? How much?\" — $249. — \"OK.\"\n\nMonth 1: 312 calls, 940ms avg latency, 86% gross margin.\n\n💡 Calculate the cost of the problem before the cost of the solution.\n\n#SaaS #BuildInPublic #AITools #Startup",
    status: 'active',
  },
  {
    _id: 'demo4',
    tone: 'Insight',
    angle: 'The 100ms rule every product builder should know',
    content: "There's one number I keep front of mind when designing anything interactive.\n\n100 milliseconds.\n\nNNGroup measured: under 100ms feels instant. Under 1 second feels normal. Over 10 seconds feels broken.\n\nFor voice AI, the threshold is even tighter. I tested this: asked 10 people to call and tell me when something felt off.\n\nUnder 800ms: nobody noticed.\n1.5–2 seconds: \"hello?\" or hangup.\n\nThis single data point cascades through every technical decision:\n→ Which STT model\n→ Sync vs async processing\n→ Streaming vs batch responses\n\nDesign decisions and architecture decisions aren't separate. They're the same decision made at different times.\n\n💡 Find the moment where latency destroys trust. Set a target in milliseconds. Let it drive your stack.\n\n#UX #ProductDesign #SaaS #AITools",
    status: 'active',
  },
  {
    _id: 'demo5',
    tone: 'Insight',
    angle: 'Why AI will reshape PMs, not replace them',
    content: "GPT-5.4 scored 75% on OSWorld-V — a real computer task benchmark. Average human: 72.4%.\n\nEveryone's reacting: \"product managers are done.\"\n\nI disagree. Here's the nuance.\n\nOSWorld-V tests well-defined tasks: \"Open Excel, find row 47, copy to Slides.\" That's execution.\n\nIt doesn't test: deciding if this presentation should exist. Sensing a stakeholder is uncomfortable. Building trust over six months.\n\nThat's judgment.\n\nThe real concern: entry-level roles are where people learned execution before developing judgment. If those roles disappear, the judgment development pipeline might too.\n\nThe path forward isn't just \"learn AI tools.\" It's \"develop judgment AI can't replicate.\"\n\n💡 What % of your work is execution? What % is judgment? Where do you want that balance in 3 years?\n\n#AITools #ProductDesign #Future #BuildInPublic",
    status: 'active',
  },
  {
    _id: 'demo6',
    tone: 'Insight',
    angle: 'Context quality = output quality',
    content: "Quality of AI output = f(quality of context you gave)\n\nThree levels of the same request:\n\nLevel 1: \"Build a flashcard system\"\n→ You get: an algorithm.\n\nLevel 2: \"Build flashcards for language learning, SM-2, localStorage\"\n→ You get: exactly what you asked for.\n\nLevel 3: \"Build flashcards for someone who studies 10 min/day and doesn't want to miss. SM-2. Zero backend.\"\n→ You get: algorithm + streak + progress + animation — and Claude explains why it added each one.\n\nDifference between Level 1 and 3: 3 extra minutes on the prompt.\nDifference in results: radical.\n\nThe template I use:\n\"[Task] for [who]. They want [goal]. Context: [when/how]. Constraints: [what not to do]. Priority: [what matters most].\"\n\n#ClaudeCode #AITools #ProductDesign #UX",
    status: 'active',
  },
  {
    _id: 'demo7',
    tone: 'tactical',
    angle: '8 AI agents, one coffee break, 40 components done',
    content: "\"Launched 8 agents and went to make coffee\" — not a metaphor. Here's what happened.\n\nTask: update token mapping for 40+ design system components. Manually: 23 hours.\n\nThe secret isn't the agents. It's the 2 hours before them:\n→ Split 40 components into 8 groups with zero interdependencies\n→ Wrote separate instructions with examples for each\n→ Created a shared read-only tokens.csv — all agents read, none modify\n\nOnly then: launched → made coffee → came back.\n\n20 minutes. 38/40 done. Two needed rework — my unclear instructions, not Claude's.\n\n4.5 hours instead of 23.\n\nFormula: quality of prep × independence of tasks = quality of output.\nTrue for AI agents. True for human teams.\n\n💡 Start with 2–3 parallel agents. Validate instruction quality at small scale first.\n\n#ClaudeCode #DesignSystems #AITools #BuildInPublic",
    status: 'active',
  },
  {
    _id: 'demo8',
    tone: 'tactical',
    angle: 'Revenue math: 86% gross margin SaaS',
    content: "The unit economics behind a $249/month B2B SaaS.\n\nMonthly cost to serve one client:\n→ Deepgram STT: $13\n→ GPT-4o mini: $8\n→ Google TTS: $32\n→ Telnyx SIP: $15\n→ Total COGS: $68/month\n\nPrice: $249/month → Gross margin at scale: 86%\n\nClient's alternatives:\n→ Human operator: $3,000/month\n→ Outsourced call center: $1,200–1,800/month\n\nClient pays $249 to save $2,951+. The product sells itself.\n\nROI formula I use before any SaaS:\nClient ROI = cost of problem / price of solution\n→ If > 3× — worth building\n→ If < 1.5× — very hard to sell\n\nFonitix ROI for client: 40×.\n\n💡 Run this math before opening Figma. 30 min in a spreadsheet are the most important 30 min of any product.\n\n#SaaS #ProductDesign #AITools #Startup",
    status: 'active',
  },
  {
    _id: 'demo9',
    tone: 'tactical',
    angle: 'GPT-5.4 vs humans: what the benchmark actually shows',
    content: "OpenAI published a number that's hard to ignore.\n\nGPT-5.4 on OSWorld-V: 75%\nAverage human on the same test: 72.4%\n\nAI outperformed the average human at computer-based work.\n\nContext that matters:\nOSWorld-V tests well-defined execution tasks: \"Open Excel, find row 47, copy to Slides.\"\n\nMore data:\n→ vs GPT-5.2: 33% fewer factual errors\n→ GDPval benchmark (44 professions): outperforms humans in 83% of tasks\n→ OpenAI 2026 inference costs: $14.1B annually\n\nThe last number: as models get more capable, each response gets more expensive. IDC forecasts 1,000× growth in inference demand by 2027.\n\nAI is getting cheaper and more expensive simultaneously — depending on task type.\n\n💡 Repetitive execution → AI wins now. Judgment calls → still human. Invest accordingly.\n\n#AITools #ProductDesign #AI #BuildInPublic",
    status: 'active',
  },
  {
    _id: 'demo10',
    tone: 'opinion',
    angle: 'Is AI actually killing entry-level jobs?',
    content: "GPT-5.4 scored 75% on a real computer task benchmark. Average human: 72.4%.\n\nA PM I know immediately said: \"I'm unemployed.\" I understand why — but I disagree.\n\nGPT-5.4 is excellent at well-defined execution: \"Open Excel, find the value, paste into Slides.\"\n\nWhat it can't do: decide if this presentation should exist. Sense that a stakeholder is uncomfortable. Build trust with a client over six months. That's judgment.\n\nThe real concern isn't \"AI will take your senior job.\" It's: \"entry-level roles — where people learned execution before developing judgment — may disappear.\"\n\nIf those roles go, where does the next generation develop judgment?\n\nThis isn't a reason to slow AI adoption. It's a reason to think deliberately about developing judgment — in yourself and your team.\n\nHow are you thinking about this?\n\n#AITools #ProductDesign #Future #Leadership",
    status: 'active',
  },
  {
    _id: 'demo11',
    tone: 'opinion',
    angle: 'Are you using AI to work faster or think better?',
    content: "There's a question I sit with.\n\nAm I using AI to work faster — or to think better?\n\nFaster: generate code, write content, automate tasks. Measurable. Easy to justify.\n\nBetter: surface assumptions I'm making. Stress-test decisions. Get perspectives I wouldn't think of alone.\n\nBoth are valuable. But I notice: most people optimize for \"faster\" because it's immediately visible. \"Better thinking\" is harder to see short-term.\n\nPrompts I use for \"thinking better\":\n→ \"What am I assuming that might be wrong?\"\n→ \"What's the strongest counterargument?\"\n→ \"What's the simplest version that proves the concept?\"\n\nMy Claude Code sessions with the most tokens weren't the ones with the most code. They were the ones with the most \"why.\"\n\n💡 Pick one decision you're about to make. Ask Claude to argue against it. See what changes.\n\n#AITools #ProductDesign #BuildInPublic #ClaudeCode",
    status: 'active',
  },
  {
    _id: 'demo12',
    tone: 'Story',
    angle: 'My AI agent took its first real call at 10:47 PM',
    content: "I wasn't planning to be online. Good thing I didn't need to be.\n\nTuesday, 10:47 PM. Someone called the restaurant to book a table.\n\nThe AI agent picked up in 890ms. Clarified the details. Confirmed the reservation. Said goodbye.\n\nI found out the next morning — from Supabase and Telnyx logs. Everything was there: timestamp (22:47:23), call duration (1:43), latency per response (890ms, 1,050ms), Stripe metering ($0.09), INSERT into reservations.\n\nThe system worked without me. Without notifications. Just did its job and left an audit trail.\n\nI'd been building this for months. Wasn't sure it would hold up in real production.\n\nIt held. At 10:47 PM. While I slept.\n\nThat's what \"autonomous system\" actually means: it doesn't need your attention to function.\n\n💡 Deploy as early as possible. The first real call teaches more than a month of staging tests.\n\n#SaaS #BuildInPublic #AITools #Fonitix",
    status: 'active',
  },
  {
    _id: 'demo13',
    tone: 'Story',
    angle: 'Client needed a website by Monday. I said yes.',
    content: "\"Can you build a premium Tesla transfer site by Monday?\"\n\nIt was Friday at 5:45 PM.\n\nFirst thought: impossible. Second thought: what specifically takes time?\n\nDesign: 1 day with no-code prototype.\nCode: 2 days with Cursor + Claude.\nDeploy: Vercel — 15 minutes.\n\nTotal: 5 days. I said: OK.\n\nSaturday: Webflow prototype. Client clicked through live pages → found 3 structural problems → fixed in 45 minutes. Same problems after 2 days of code: 6+ hours minimum.\n\nSunday: Cursor + Claude. Full frontend in 6 hours.\n\nMonday 9 AM: deployed, custom domain, handoff complete.\n\nAgency alternative: 3–4 weeks, $2,000–5,000.\n\nBetween my decision and the live product: zero people, zero handoffs, zero broken telephone.\n\n#BuildInPublic #ProductDesign #AITools #DesignEngineering",
    status: 'active',
  },
  {
    _id: 'demo14',
    tone: 'Story',
    angle: 'The bug invisible to the admin',
    content: "A type of bug that's hardest to find. Not because it's complex — but because nothing breaks. It just returns empty.\n\nOne week after launch. Client: \"agent accepted the reservation but the kitchen sees nothing.\"\n\nChecked from my admin account: reservation in database. Realtime subscription: silent.\n\nOne hour of debugging. Everything looks fine.\n\nThen I logged in as a \"kitchen-user\" test account.\n\nEmpty. No error. Just empty.\n\nCause: forgot to add RLS SELECT policy for kitchen-user. Database silently returned an empty array.\n\nI'd been testing from my admin account the whole time. Admin sees everything. kitchen-user sees only what's permitted.\n\nFix: one line of SQL, 10 minutes.\n\nLesson: for every role — a separate test account. Before every deploy — test from every role. Admin is for debugging, not UX verification.\n\n#SaaS #ProductDesign #DesignEngineering #BuildInPublic",
    status: 'active',
  },
  {
    _id: 'demo15',
    tone: 'Story',
    angle: 'Saturday night, I wanted to build something',
    content: "Saturday 9 PM. Decided to build a language learning app. By 11:30 PM — deployed.\n\nFirst prompt to Claude Code:\n\"Build a flashcard app for language learning. The person studies 10 min/day and doesn't want to miss days. SM-2 algorithm. Zero backend for MVP.\"\n\nKey phrase: \"doesn't want to miss days.\" Behavior goal, not a feature request.\n\n12 minutes later — the response.\n\nSM-2 ✓, localStorage ✓, streak counter (didn't ask), flip animation (didn't ask), \"cards remaining today\" counter (didn't ask).\n\nClaude read \"doesn't want to miss days\" and added streak + progress — logically necessary for that goal.\n\nIt didn't complete a task. It solved the problem I described.\n\nDifference: \"implement an algorithm\" vs \"person wants to achieve X.\"\nOne gets a feature. The other gets a product.\n\n💡 Start prompts with: \"I want [who] to [do what] and feel [how].\" See what changes.\n\n#ClaudeCode #BuildInPublic #ProductDesign #AITools",
    status: 'active',
  },
];

function postChipStyle(active: boolean): CSSProperties {
  return { padding: '5px 14px', borderRadius: 20, fontSize: 12.5, fontWeight: 500, cursor: 'pointer', border: active ? '1px solid var(--ac)' : '1px solid var(--bd)', background: active ? 'rgba(107,79,255,.15)' : 'var(--s1)', color: active ? 'var(--ac2)' : 'var(--t3)', transition: 'all .15s', fontFamily: 'var(--head)', textTransform: 'capitalize' as const };
}
function postToneBadgeStyle(tone: string): CSSProperties {
  return { padding: '3px 10px', borderRadius: 12, fontSize: 11, fontWeight: 700, background: `${toneColor(tone)}22`, color: toneColor(tone), border: `1px solid ${toneColor(tone)}44`, letterSpacing: '.3px', textTransform: 'uppercase' as const, flexShrink: 0 };
}
function skeletonLineStyle(w: string, h = 12): CSSProperties {
  return { height: h, background: 'var(--s3)', borderRadius: 4, width: w };
}

const s: Record<string, CSSProperties> = {
  root: {
    padding: 24,
    animation: 'fadeIn .2s ease',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    flexWrap: 'wrap' as const,
    gap: 12,
  },
  chips: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap' as const,
  },
  generateBtn: {
    padding: '9px 20px',
    background: 'var(--ac)',
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--r)',
    fontFamily: 'var(--head)',
    fontSize: 13.5,
    fontWeight: 700,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    transition: 'all .15s',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 16,
  },
  card: {
    background: 'var(--s1)',
    border: '1px solid var(--bd)',
    borderRadius: 'var(--r2)',
    padding: 20,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 12,
    transition: 'border-color .2s',
    animation: 'fadeIn .25s ease',
  },
  cardTop: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  charCount: {
    fontSize: 11,
    color: 'var(--t3)',
    fontFamily: 'var(--mono)',
  },
  angle: {
    fontSize: 12.5,
    color: 'var(--t3)',
    fontStyle: 'italic',
    lineHeight: 1.4,
  },
  content: {
    fontSize: 13.5,
    color: 'var(--t2)',
    lineHeight: 1.65,
    display: '-webkit-box',
    WebkitLineClamp: 5,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
    cursor: 'pointer',
  },
  contentExpanded: {
    fontSize: 13.5,
    color: 'var(--t2)',
    lineHeight: 1.65,
    whiteSpace: 'pre-wrap' as const,
    cursor: 'pointer',
  },
  actions: {
    display: 'flex',
    gap: 6,
    marginTop: 'auto',
  },
  actionBtn: {
    flex: 1,
    padding: '7px 0',
    background: 'var(--s2)',
    border: '1px solid var(--bd)',
    borderRadius: 'var(--r)',
    color: 'var(--t3)',
    fontFamily: 'var(--head)',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all .15s',
  },
  deleteBtn: {
    padding: '7px 10px',
    background: 'none',
    border: '1px solid var(--bd)',
    borderRadius: 'var(--r)',
    color: 'var(--t3)',
    fontFamily: 'var(--head)',
    fontSize: 12,
    cursor: 'pointer',
    transition: 'all .15s',
  },
  skeletonCard: {
    background: 'var(--s1)',
    border: '1px solid var(--bd)',
    borderRadius: 'var(--r2)',
    padding: 20,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 12,
    animation: 'pulse 1.5s ease-in-out infinite',
  },
  emptyState: {
    gridColumn: '1 / -1',
    textAlign: 'center' as const,
    padding: '60px 20px',
  },
  emptyIcon: {
    fontSize: 40,
    marginBottom: 16,
    opacity: 0.3,
  },
  emptyTitle: {
    fontFamily: 'var(--head)',
    fontSize: 17,
    fontWeight: 600,
    color: 'var(--t2)',
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 14,
    color: 'var(--t3)',
    marginBottom: 24,
    lineHeight: 1.6,
  },
  genBtnLarge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '12px 28px',
    background: 'var(--ac)',
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--r)',
    fontFamily: 'var(--head)',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all .15s',
  },
  scheduleModal: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(0,0,0,.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 200,
    backdropFilter: 'blur(4px)',
  },
  scheduleCard: {
    background: 'var(--s1)',
    border: '1px solid var(--bd2)',
    borderRadius: 'var(--r2)',
    padding: 28,
    width: 340,
    maxWidth: '95vw',
  },
  modalTitle: {
    fontFamily: 'var(--head)',
    fontSize: 16,
    fontWeight: 700,
    color: 'var(--t1)',
    marginBottom: 16,
  },
  modalLabel: {
    fontSize: 13,
    color: 'var(--t2)',
    fontWeight: 500,
    marginBottom: 6,
    display: 'block',
  },
  modalInput: {
    width: '100%',
    padding: '10px 14px',
    background: 'var(--s2)',
    border: '1px solid var(--bd)',
    borderRadius: 'var(--r)',
    color: 'var(--t1)',
    fontSize: 14,
    outline: 'none',
    marginBottom: 16,
    fontFamily: 'var(--head)',
  },
  modalBtns: {
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
  },
};

interface ScheduleModal {
  postId: string;
  content: string;
}

export default function PostsView({ user, prefs, search, demoMode, autoGenerate, onAutoGenerateDone }: Props) {
  const [toneFilter, setToneFilter] = useState('all');
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [scheduleModal, setScheduleModal] = useState<ScheduleModal | null>(null);
  const [scheduleDate, setScheduleDate] = useState('');
  const [copied, setCopied] = useState<string | null>(null);
  const { t } = useUILang();

  const rawPosts = useQuery(
    api.posts.getPosts,
    !demoMode ? { userId: user._id as any, status: 'active' as const } : 'skip'
  );

  const posts = demoMode ? DEMO_POSTS : (rawPosts ?? []);

  useEffect(() => {
    if (autoGenerate && prefs?.apikey?.startsWith('sk-') && rawPosts !== undefined && rawPosts.length === 0 && !generating) {
      handleGenerate(18);
      onAutoGenerateDone?.();
    }
  }, [autoGenerate, rawPosts, prefs?.apikey]);

  const generatePostsAction = useAction(api.ai.generatePosts);
  const createManyPosts = useMutation(api.posts.createManyPosts);
  const deletePostMut = useMutation(api.posts.deletePost);
  const setStatus = useMutation(api.posts.setStatus);
  const upsertPrefs = useMutation(api.users.upsertPrefs);

  const hasApiKey = prefs?.apikey?.startsWith('sk-ant');

  const filteredPosts = posts.filter(p => {
    if (toneFilter !== 'all') {
      if (!p.tone.toLowerCase().includes(toneFilter.toLowerCase())) return false;
    }
    if (search) {
      const q = search.toLowerCase();
      return (
        p.content.toLowerCase().includes(q) ||
        p.angle.toLowerCase().includes(q) ||
        p.tone.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const handleGenerate = async (count = 9) => {
    if (!prefs?.apikey || !hasApiKey) return;
    setGenerating(true);
    setGenerateError(null);
    try {
      const generated = await generatePostsAction({
        userId: user._id as any,
        apiKey: prefs.apikey,
        profile: {
          name: prefs.name || undefined,
          role: prefs.role || undefined,
          bio: prefs.bio || undefined,
          projects: prefs.projects || undefined,
          stack: prefs.stack || undefined,
          audience: prefs.audience || undefined,
          tone: prefs.tone || undefined,
          avoid: prefs.avoid || undefined,
          contentPillars: prefs.contentPillars || undefined,
        },
        lang: prefs.lang || 'English',
        count,
      });
      await createManyPosts({
        userId: user._id as any,
        posts: generated,
      });
    } catch (e) {
      console.error('Generation failed:', e);
      setGenerateError(e instanceof Error ? e.message : 'Generation failed');
    } finally {
      setGenerating(false);
    }
  };

  const handleDelete = async (postId: string) => {
    if (demoMode) return;
    await deletePostMut({ postId: postId as any });
  };

  const handleCopy = (postId: string, content: string) => {
    navigator.clipboard.writeText(content).then(() => {
      setCopied(postId);
      setTimeout(() => setCopied(null), 2000);
    });
  };

  const handleSchedule = (postId: string, content: string) => {
    if (demoMode) return;
    setScheduleModal({ postId, content });
    const d = new Date();
    d.setDate(d.getDate() + 1);
    setScheduleDate(d.toISOString().slice(0, 10));
  };

  const confirmSchedule = async () => {
    if (!scheduleModal || !scheduleDate) return;
    await setStatus({
      postId: scheduleModal.postId as any,
      status: 'scheduled',
      scheduledDate: scheduleDate,
    });
    setScheduleModal(null);
  };

  const isLoading = !demoMode && rawPosts === undefined;
  const isEmpty = !isLoading && !generating && posts.length === 0;

  const handlePostLangChange = async (langCode: string) => {
    if (demoMode || !prefs) return;
    await upsertPrefs({
      userId: user._id as any,
      name: prefs.name || user.name,
      lang: langCode,
    });
  };

  return (
    <div style={s.root}>
      <div style={s.toolbar}>
        <div style={s.chips}>
          {TONES.map(tone => (
            <button
              key={tone}
              style={postChipStyle(toneFilter === tone)}
              onClick={() => setToneFilter(tone)}
            >
              {tone}
            </button>
          ))}
        </div>
        {hasApiKey && !demoMode && (
          <button
            style={{ ...s.generateBtn, opacity: generating ? 0.7 : 1 }}
            onClick={() => handleGenerate(18)}
            disabled={generating}
            onMouseEnter={e => { if (!generating) e.currentTarget.style.background = 'var(--ac2)'; }}
            onMouseLeave={e => (e.currentTarget.style.background = 'var(--ac)')}
          >
            {generating ? (
              <>
                <span style={{ display: 'inline-block', animation: 'spin 1s linear infinite' }}>⟳</span>
                {t('generating')}
              </>
            ) : t('generate_posts')}
          </button>
        )}
      </div>

      {!demoMode && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
          {POST_LANGUAGES.map(l => (
            <button
              key={l.code}
              style={postChipStyle((prefs?.lang ?? 'English') === l.code)}
              onClick={() => handlePostLangChange(l.code)}
            >
              {l.label}
            </button>
          ))}
        </div>
      )}

      {generateError && (
        <div style={{ margin: '0 0 16px', padding: '10px 16px', background: 'rgba(239,68,68,.08)', border: '1px solid rgba(239,68,68,.25)', borderRadius: 'var(--r)', color: 'var(--err)', fontSize: 13 }}>
          ✕ {generateError}
        </div>
      )}

      <div style={s.grid}>
        {generating && Array.from({ length: 9 }).map((_, i) => (
          <div key={`sk-${i}`} style={s.skeletonCard}>
            <div style={{ display: 'flex', gap: 8 }}>
              <div style={skeletonLineStyle('25%', 18)} />
              <div style={{ flex: 1 }} />
              <div style={skeletonLineStyle('15%', 14)} />
            </div>
            <div style={skeletonLineStyle('80%', 11)} />
            <div style={{ display: 'flex', flexDirection: 'column' as const, gap: 6 }}>
              <div style={skeletonLineStyle('100%')} />
              <div style={skeletonLineStyle('90%')} />
              <div style={skeletonLineStyle('95%')} />
              <div style={skeletonLineStyle('70%')} />
            </div>
          </div>
        ))}

        {!generating && filteredPosts.map(post => {
          const isExpanded = expandedId === post._id;
          const hashtags = (post.content.match(/#\w+/g) || []);
          const bodyText = post.content.replace(/(#\w+\s*)+$/, '').trimEnd();
          return (
            <div
              key={post._id}
              style={s.card}
              onMouseEnter={e => (e.currentTarget.style.borderColor = 'rgba(107,79,255,.25)')}
              onMouseLeave={e => (e.currentTarget.style.borderColor = 'var(--bd)')}
            >
              <div style={s.cardTop}>
                <span style={postToneBadgeStyle(post.tone)}>{post.tone}</span>
                <span style={s.charCount}>{post.content.length}c</span>
              </div>

              <div style={s.angle}>{post.angle.replace(/_/g, ' ')}</div>

              <div
                style={isExpanded ? s.contentExpanded : s.content}
                onClick={() => setExpandedId(isExpanded ? null : post._id)}
                title={isExpanded ? 'Click to collapse' : 'Click to expand'}
              >
                {isExpanded ? post.content : bodyText}
              </div>

              {hashtags.length > 0 && (
                <div style={{ display: 'flex', flexWrap: 'wrap' as const, gap: 4 }}>
                  {hashtags.slice(0, 6).map(tag => (
                    <span
                      key={tag}
                      style={{
                        fontSize: 10.5,
                        color: 'var(--ac2)',
                        background: 'rgba(107,79,255,.08)',
                        border: '1px solid rgba(107,79,255,.2)',
                        borderRadius: 10,
                        padding: '2px 8px',
                        fontWeight: 500,
                      }}
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              )}

              {isExpanded && (
                <div style={{ fontSize: 11, color: 'var(--t3)', textAlign: 'right' as const }}>
                  {t('click_to_collapse')}
                </div>
              )}

              <div style={s.actions}>
                <button
                  style={{
                    ...s.actionBtn,
                    ...(copied === post._id ? { color: 'var(--ok)', borderColor: 'var(--ok)' } : {}),
                  }}
                  onClick={() => handleCopy(post._id, post.content)}
                  onMouseEnter={e => {
                    if (copied !== post._id) {
                      e.currentTarget.style.background = 'var(--s3)';
                      e.currentTarget.style.color = 'var(--t2)';
                    }
                  }}
                  onMouseLeave={e => {
                    if (copied !== post._id) {
                      e.currentTarget.style.background = 'var(--s2)';
                      e.currentTarget.style.color = 'var(--t3)';
                    }
                  }}
                >
                  {copied === post._id ? t('copied') : t('copy')}
                </button>
                <button
                  style={s.actionBtn}
                  onClick={() => handleSchedule(post._id, post.content)}
                  disabled={demoMode}
                  title={demoMode ? 'Sign in to schedule' : 'Schedule post'}
                  onMouseEnter={e => {
                    e.currentTarget.style.background = 'var(--s3)';
                    e.currentTarget.style.color = 'var(--t2)';
                  }}
                  onMouseLeave={e => {
                    e.currentTarget.style.background = 'var(--s2)';
                    e.currentTarget.style.color = 'var(--t3)';
                  }}
                >
                  {t('schedule_post')}
                </button>
                <button
                  style={s.deleteBtn}
                  onClick={() => handleDelete(post._id)}
                  disabled={demoMode}
                  title="Delete post"
                  onMouseEnter={e => {
                    e.currentTarget.style.color = 'var(--err)';
                    e.currentTarget.style.borderColor = 'rgba(239,68,68,.3)';
                  }}
                  onMouseLeave={e => {
                    e.currentTarget.style.color = 'var(--t3)';
                    e.currentTarget.style.borderColor = 'var(--bd)';
                  }}
                >
                  ✕
                </button>
              </div>
            </div>
          );
        })}

        {isEmpty && (
          <div style={s.emptyState}>
            <div style={s.emptyIcon}>◈</div>
            <div style={s.emptyTitle}>
              {hasApiKey ? t('ready_to_generate') : t('no_posts_yet')}
            </div>
            <div style={s.emptyText}>
              {hasApiKey
                ? t('ready_to_generate_hint')
                : t('add_api_key_hint')}
            </div>
            {hasApiKey && !demoMode && (
              <button
                style={s.genBtnLarge}
                onClick={() => handleGenerate(18)}
                onMouseEnter={e => (e.currentTarget.style.background = 'var(--ac2)')}
                onMouseLeave={e => (e.currentTarget.style.background = 'var(--ac)')}
              >
                {t('generate_18')}
              </button>
            )}
          </div>
        )}
      </div>

      {/* Schedule Modal */}
      {scheduleModal && (
        <div style={s.scheduleModal} onClick={() => setScheduleModal(null)}>
          <div style={s.scheduleCard} onClick={e => e.stopPropagation()}>
            <div style={s.modalTitle}>{t('schedule_post_title')}</div>
            <label style={s.modalLabel}>{t('date_label')}</label>
            <input
              style={s.modalInput}
              type="date"
              value={scheduleDate}
              onChange={e => setScheduleDate(e.target.value)}
              min={new Date().toISOString().slice(0, 10)}
            />
            <div style={s.modalBtns}>
              <button
                style={{
                  padding: '9px 18px',
                  background: 'none',
                  border: '1px solid var(--bd)',
                  borderRadius: 'var(--r)',
                  color: 'var(--t2)',
                  fontFamily: 'var(--head)',
                  fontSize: 13,
                  cursor: 'pointer',
                }}
                onClick={() => setScheduleModal(null)}
              >
                {t('cancel')}
              </button>
              <button
                style={{
                  padding: '9px 18px',
                  background: 'var(--ac)',
                  border: 'none',
                  borderRadius: 'var(--r)',
                  color: '#fff',
                  fontFamily: 'var(--head)',
                  fontSize: 13,
                  fontWeight: 700,
                  cursor: 'pointer',
                }}
                onClick={confirmSchedule}
              >
                {t('schedule_post')}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
